onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mips_tb/ALU_result_out
add wave -noupdate /mips_tb/Branch_out
add wave -noupdate /mips_tb/Instruction_out
add wave -noupdate /mips_tb/Memwrite_out
add wave -noupdate /mips_tb/PC
add wave -noupdate /mips_tb/Regwrite_out
add wave -noupdate /mips_tb/Zero_out
add wave -noupdate /mips_tb/clock
add wave -noupdate /mips_tb/read_data_1_out
add wave -noupdate /mips_tb/read_data_2_out
add wave -noupdate /mips_tb/reset
add wave -noupdate /mips_tb/write_data_out
add wave -noupdate /mips_tb/KEY1
add wave -noupdate /mips_tb/KEY2
add wave -noupdate /mips_tb/KEY3
add wave -noupdate /mips_tb/Switches
add wave -noupdate /mips_tb/LEDG_out
add wave -noupdate /mips_tb/LEDR_out
add wave -noupdate /mips_tb/HEX0_out
add wave -noupdate /mips_tb/HEX1_out
add wave -noupdate /mips_tb/HEX2_out
add wave -noupdate /mips_tb/HEX3_out
add wave -noupdate /mips_tb/Zero4LEDR
add wave -noupdate /mips_tb/U_0/reset
add wave -noupdate /mips_tb/U_0/clk_24Mhz
add wave -noupdate /mips_tb/U_0/PC
add wave -noupdate /mips_tb/U_0/ALU_result_out
add wave -noupdate /mips_tb/U_0/read_data_1_out
add wave -noupdate /mips_tb/U_0/read_data_2_out
add wave -noupdate /mips_tb/U_0/write_data_out
add wave -noupdate /mips_tb/U_0/Instruction_out
add wave -noupdate /mips_tb/U_0/Branch_out
add wave -noupdate /mips_tb/U_0/Zero_out
add wave -noupdate /mips_tb/U_0/Memwrite_out
add wave -noupdate /mips_tb/U_0/Regwrite_out
add wave -noupdate /mips_tb/U_0/ENABLE
add wave -noupdate /mips_tb/U_0/KEY1
add wave -noupdate /mips_tb/U_0/KEY2
add wave -noupdate /mips_tb/U_0/KEY3
add wave -noupdate /mips_tb/U_0/Switches
add wave -noupdate /mips_tb/U_0/LEDG_out
add wave -noupdate /mips_tb/U_0/LEDR_out
add wave -noupdate /mips_tb/U_0/HEX0_out
add wave -noupdate /mips_tb/U_0/HEX1_out
add wave -noupdate /mips_tb/U_0/HEX2_out
add wave -noupdate /mips_tb/U_0/HEX3_out
add wave -noupdate /mips_tb/U_0/Zero4LEDR
add wave -noupdate /mips_tb/U_0/PC_plus_4
add wave -noupdate /mips_tb/U_0/read_data_1
add wave -noupdate /mips_tb/U_0/read_data_2
add wave -noupdate /mips_tb/U_0/Sign_Extend
add wave -noupdate /mips_tb/U_0/Add_result
add wave -noupdate /mips_tb/U_0/ALU_result
add wave -noupdate /mips_tb/U_0/read_data
add wave -noupdate /mips_tb/U_0/ALUSrc
add wave -noupdate /mips_tb/U_0/Branch_eq
add wave -noupdate /mips_tb/U_0/Branch_neq
add wave -noupdate /mips_tb/U_0/RegDst
add wave -noupdate /mips_tb/U_0/Regwrite
add wave -noupdate /mips_tb/U_0/Zero
add wave -noupdate /mips_tb/U_0/MemWrite
add wave -noupdate /mips_tb/U_0/MemtoReg
add wave -noupdate /mips_tb/U_0/MemRead
add wave -noupdate /mips_tb/U_0/Jump
add wave -noupdate /mips_tb/U_0/isJR
add wave -noupdate /mips_tb/U_0/ALUop
add wave -noupdate /mips_tb/U_0/Instruction
add wave -noupdate /mips_tb/U_0/Address_ALU_res
add wave -noupdate /mips_tb/U_0/HEX0_tmp
add wave -noupdate /mips_tb/U_0/HEX1_tmp
add wave -noupdate /mips_tb/U_0/HEX2_tmp
add wave -noupdate /mips_tb/U_0/HEX3_tmp
add wave -noupdate /mips_tb/U_0/IO_out
add wave -noupdate /mips_tb/U_0/read_data_tmp
add wave -noupdate /mips_tb/U_0/MemWrite_mem
add wave -noupdate /mips_tb/U_0/MemRead_mem
add wave -noupdate /mips_tb/U_0/ioWrite
add wave -noupdate /mips_tb/U_0/ioRead
add wave -noupdate /mips_tb/U_0/BTCTL_W
add wave -noupdate /mips_tb/U_0/BTCTL_R
add wave -noupdate /mips_tb/U_0/BTCNT_W
add wave -noupdate /mips_tb/U_0/BTCNT_R
add wave -noupdate /mips_tb/U_0/BTIFG
add wave -noupdate /mips_tb/U_0/CS
add wave -noupdate /mips_tb/U_0/INTA
add wave -noupdate /mips_tb/U_0/INTR_synced
add wave -noupdate /mips_tb/U_0/INTR
add wave -noupdate /mips_tb/U_0/IE_W
add wave -noupdate /mips_tb/U_0/IE_R
add wave -noupdate /mips_tb/U_0/IFG_W
add wave -noupdate /mips_tb/U_0/IFG_R
add wave -noupdate /mips_tb/U_0/IFG_writebit
add wave -noupdate /mips_tb/U_0/ISR_MemAdrs
add wave -noupdate /mips_tb/U_0/PC_tmp
add wave -noupdate /mips_tb/U_0/KEY1_inv
add wave -noupdate /mips_tb/U_0/KEY2_inv
add wave -noupdate /mips_tb/U_0/KEY3_inv
add wave -noupdate /mips_tb/U_0/clock
add wave -noupdate /mips_tb/U_0/reset_inv
add wave -noupdate /mips_tb/U_0/IFE/Instruction
add wave -noupdate /mips_tb/U_0/IFE/PC_plus_4_out
add wave -noupdate /mips_tb/U_0/IFE/Add_result
add wave -noupdate /mips_tb/U_0/IFE/Branch_eq
add wave -noupdate /mips_tb/U_0/IFE/Branch_neq
add wave -noupdate /mips_tb/U_0/IFE/Zero
add wave -noupdate /mips_tb/U_0/IFE/Jump
add wave -noupdate /mips_tb/U_0/IFE/isJR
add wave -noupdate /mips_tb/U_0/IFE/PC_out
add wave -noupdate /mips_tb/U_0/IFE/INTR
add wave -noupdate /mips_tb/U_0/IFE/INTA
add wave -noupdate /mips_tb/U_0/IFE/ISR_adrs
add wave -noupdate /mips_tb/U_0/IFE/clock
add wave -noupdate /mips_tb/U_0/IFE/reset
add wave -noupdate /mips_tb/U_0/IFE/PC
add wave -noupdate /mips_tb/U_0/IFE/PC_plus_4
add wave -noupdate /mips_tb/U_0/IFE/Mem_Addr
add wave -noupdate /mips_tb/U_0/IFE/next_PC
add wave -noupdate /mips_tb/U_0/IFE/Instruction_tmp
add wave -noupdate /mips_tb/U_0/IFE/INTR_old
add wave -noupdate /mips_tb/U_0/IFE/tmp_intr
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/wren_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/wren_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/rden_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/rden_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/data_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/data_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/address_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/address_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/clock0
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/clock1
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/clocken0
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/clocken1
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/clocken2
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/clocken3
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/aclr0
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/aclr1
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/addressstall_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/addressstall_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/byteena_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/byteena_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/q_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/q_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/eccstatus
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_data_reg_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_data_reg_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_q_reg_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_q_tmp_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_q_tmp2_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_q_tmp_wren_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_q_tmp2_wren_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_q_tmp_wren_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_q_reg_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_q_tmp_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_q_tmp2_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_q_output_latch
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_q_ecc_reg_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_q_ecc_tmp_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_current_written_data_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_original_data_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_original_data_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_byteena_mask_reg_a_x
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_byteena_mask_reg_b_x
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_byteena_mask_reg_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_byteena_mask_reg_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_byteena_mask_reg_a_out
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_byteena_mask_reg_b_out
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_byteena_mask_reg_a_out_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_byteena_mask_reg_b_out_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_address_reg_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_address_reg_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_wren_reg_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_wren_reg_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_rden_reg_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_rden_reg_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_read_flag_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_read_flag_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_reread_flag_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_reread_flag_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_reread_flag2_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_reread_flag2_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_write_flag_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_write_flag_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_nmram_write_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_nmram_write_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_indata_aclr_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_address_aclr_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_wrcontrol_aclr_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_indata_aclr_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_address_aclr_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_wrcontrol_aclr_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_outdata_aclr_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_outdata_aclr_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_rdcontrol_aclr_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_byteena_aclr_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_byteena_aclr_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/good_to_go_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/good_to_go_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_core_clocken_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_core_clocken_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_core_clocken_b0
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_core_clocken_b1
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_inclocken0
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_input_clocken_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_outdata_clken_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_outdata_clken_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_outlatch_clken_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_outlatch_clken_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_core_clocken_a_reg
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_core_clocken_b_reg
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/default_val
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_data_zero_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_data_zero_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_data_ones_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_data_ones_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/same_clock_pulse0
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/same_clock_pulse1
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_force_reread_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_force_reread_a1
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_force_reread_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_force_reread_b1
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_force_reread_signal_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_force_reread_signal_b
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_good_to_write_a
add wave -noupdate /mips_tb/U_0/IFE/inst_memory/i_good_to_write_b
add wave -noupdate /mips_tb/U_0/ID/read_data_1
add wave -noupdate /mips_tb/U_0/ID/read_data_2
add wave -noupdate /mips_tb/U_0/ID/Instruction
add wave -noupdate /mips_tb/U_0/ID/read_data
add wave -noupdate /mips_tb/U_0/ID/ALU_result
add wave -noupdate /mips_tb/U_0/ID/RegWrite
add wave -noupdate /mips_tb/U_0/ID/MemtoReg
add wave -noupdate /mips_tb/U_0/ID/RegDst
add wave -noupdate /mips_tb/U_0/ID/Sign_extend
add wave -noupdate /mips_tb/U_0/ID/IntrptCS
add wave -noupdate /mips_tb/U_0/ID/Return_PC
add wave -noupdate /mips_tb/U_0/ID/clock
add wave -noupdate /mips_tb/U_0/ID/reset
add wave -noupdate /mips_tb/U_0/ID/register_array
add wave -noupdate /mips_tb/U_0/ID/write_register_address
add wave -noupdate /mips_tb/U_0/ID/write_data
add wave -noupdate /mips_tb/U_0/ID/read_register_1_address
add wave -noupdate /mips_tb/U_0/ID/read_register_2_address
add wave -noupdate /mips_tb/U_0/ID/write_register_address_1
add wave -noupdate /mips_tb/U_0/ID/write_register_address_0
add wave -noupdate /mips_tb/U_0/ID/Instruction_immediate_value
add wave -noupdate /mips_tb/U_0/ID/GIE
add wave -noupdate /mips_tb/U_0/CTL/Opcode
add wave -noupdate /mips_tb/U_0/CTL/Fun_op
add wave -noupdate /mips_tb/U_0/CTL/RegDst
add wave -noupdate /mips_tb/U_0/CTL/ALUSrc
add wave -noupdate /mips_tb/U_0/CTL/MemtoReg
add wave -noupdate /mips_tb/U_0/CTL/RegWrite
add wave -noupdate /mips_tb/U_0/CTL/MemRead
add wave -noupdate /mips_tb/U_0/CTL/MemWrite
add wave -noupdate /mips_tb/U_0/CTL/Branch_eq
add wave -noupdate /mips_tb/U_0/CTL/Branch_neq
add wave -noupdate /mips_tb/U_0/CTL/ALUop
add wave -noupdate /mips_tb/U_0/CTL/Jump
add wave -noupdate /mips_tb/U_0/CTL/isJR
add wave -noupdate /mips_tb/U_0/CTL/clock
add wave -noupdate /mips_tb/U_0/CTL/reset
add wave -noupdate /mips_tb/U_0/CTL/R_format
add wave -noupdate /mips_tb/U_0/CTL/Lw
add wave -noupdate /mips_tb/U_0/CTL/Sw
add wave -noupdate /mips_tb/U_0/CTL/Beq
add wave -noupdate /mips_tb/U_0/CTL/I_format
add wave -noupdate /mips_tb/U_0/CTL/Bnq
add wave -noupdate /mips_tb/U_0/CTL/isJAL
add wave -noupdate /mips_tb/U_0/CTL/INTR
add wave -noupdate /mips_tb/U_0/EXE/Read_data_1
add wave -noupdate /mips_tb/U_0/EXE/Read_data_2
add wave -noupdate /mips_tb/U_0/EXE/Sign_extend
add wave -noupdate /mips_tb/U_0/EXE/Function_opcode
add wave -noupdate /mips_tb/U_0/EXE/Opcode
add wave -noupdate /mips_tb/U_0/EXE/ALUOp
add wave -noupdate /mips_tb/U_0/EXE/Jump
add wave -noupdate /mips_tb/U_0/EXE/isJR
add wave -noupdate /mips_tb/U_0/EXE/ALUSrc
add wave -noupdate /mips_tb/U_0/EXE/Zero
add wave -noupdate /mips_tb/U_0/EXE/ALU_Result
add wave -noupdate /mips_tb/U_0/EXE/Add_Result
add wave -noupdate /mips_tb/U_0/EXE/PC_plus_4
add wave -noupdate /mips_tb/U_0/EXE/clock
add wave -noupdate /mips_tb/U_0/EXE/reset
add wave -noupdate /mips_tb/U_0/EXE/Ainput
add wave -noupdate /mips_tb/U_0/EXE/Binput
add wave -noupdate /mips_tb/U_0/EXE/ALU_output_mux
add wave -noupdate /mips_tb/U_0/EXE/Branch_Add
add wave -noupdate /mips_tb/U_0/EXE/ALU_ctl
add wave -noupdate /mips_tb/U_0/EXE/Shamt
add wave -noupdate /mips_tb/U_0/EXE/RLA_out
add wave -noupdate /mips_tb/U_0/EXE/RRA_out
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/x
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/res
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/xl1
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/xl2
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/xl4
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/reg0to1
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/reg1to2
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/sy
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/x0
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/x1
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/yout
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(0)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(0)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(0)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(0)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(1)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(1)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(1)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(1)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(2)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(2)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(2)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(2)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(3)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(3)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(3)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(3)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(4)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(4)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(4)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(4)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(5)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(5)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(5)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(5)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(6)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(6)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(6)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(6)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(7)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(7)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(7)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(7)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(8)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(8)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(8)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(8)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(9)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(9)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(9)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(9)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(10)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(10)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(10)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(10)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(11)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(11)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(11)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(11)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(12)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(12)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(12)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(12)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(13)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(13)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(13)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(13)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(14)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(14)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(14)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(14)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(15)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(15)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(15)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(15)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(16)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(16)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(16)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(16)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(17)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(17)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(17)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(17)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(18)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(18)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(18)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(18)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(19)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(19)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(19)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(19)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(20)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(20)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(20)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(20)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(21)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(21)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(21)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(21)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(22)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(22)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(22)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(22)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(23)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(23)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(23)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(23)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(24)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(24)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(24)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(24)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(25)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(25)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(25)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(25)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(26)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(26)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(26)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(26)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(27)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(27)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(27)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(27)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(28)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(28)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(28)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(28)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(29)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(29)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(29)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(29)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(30)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(30)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(30)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(30)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(31)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(31)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(31)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create0/create(31)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/sy
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/x0
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/x1
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/yout
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(0)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(0)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(0)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(0)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(1)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(1)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(1)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(1)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(2)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(2)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(2)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(2)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(3)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(3)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(3)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(3)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(4)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(4)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(4)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(4)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(5)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(5)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(5)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(5)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(6)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(6)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(6)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(6)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(7)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(7)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(7)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(7)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(8)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(8)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(8)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(8)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(9)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(9)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(9)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(9)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(10)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(10)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(10)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(10)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(11)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(11)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(11)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(11)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(12)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(12)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(12)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(12)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(13)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(13)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(13)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(13)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(14)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(14)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(14)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(14)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(15)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(15)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(15)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(15)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(16)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(16)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(16)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(16)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(17)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(17)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(17)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(17)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(18)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(18)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(18)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(18)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(19)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(19)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(19)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(19)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(20)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(20)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(20)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(20)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(21)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(21)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(21)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(21)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(22)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(22)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(22)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(22)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(23)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(23)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(23)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(23)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(24)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(24)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(24)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(24)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(25)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(25)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(25)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(25)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(26)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(26)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(26)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(26)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(27)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(27)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(27)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(27)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(28)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(28)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(28)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(28)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(29)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(29)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(29)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(29)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(30)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(30)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(30)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(30)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(31)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(31)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(31)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create1/create(31)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/sy
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/x0
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/x1
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/yout
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(0)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(0)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(0)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(0)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(1)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(1)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(1)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(1)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(2)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(2)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(2)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(2)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(3)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(3)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(3)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(3)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(4)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(4)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(4)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(4)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(5)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(5)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(5)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(5)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(6)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(6)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(6)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(6)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(7)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(7)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(7)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(7)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(8)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(8)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(8)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(8)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(9)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(9)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(9)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(9)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(10)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(10)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(10)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(10)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(11)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(11)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(11)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(11)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(12)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(12)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(12)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(12)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(13)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(13)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(13)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(13)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(14)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(14)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(14)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(14)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(15)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(15)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(15)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(15)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(16)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(16)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(16)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(16)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(17)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(17)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(17)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(17)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(18)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(18)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(18)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(18)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(19)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(19)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(19)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(19)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(20)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(20)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(20)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(20)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(21)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(21)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(21)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(21)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(22)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(22)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(22)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(22)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(23)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(23)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(23)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(23)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(24)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(24)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(24)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(24)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(25)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(25)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(25)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(25)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(26)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(26)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(26)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(26)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(27)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(27)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(27)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(27)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(28)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(28)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(28)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(28)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(29)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(29)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(29)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(29)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(30)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(30)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(30)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(30)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(31)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(31)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(31)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_L/create2/create(31)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/x
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/res
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/xl1
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/xl2
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/xl4
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/reg0to1
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/reg1to2
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/sy
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/x0
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/x1
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/yout
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(0)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(0)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(0)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(0)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(1)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(1)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(1)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(1)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(2)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(2)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(2)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(2)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(3)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(3)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(3)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(3)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(4)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(4)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(4)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(4)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(5)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(5)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(5)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(5)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(6)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(6)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(6)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(6)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(7)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(7)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(7)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(7)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(8)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(8)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(8)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(8)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(9)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(9)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(9)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(9)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(10)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(10)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(10)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(10)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(11)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(11)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(11)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(11)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(12)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(12)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(12)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(12)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(13)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(13)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(13)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(13)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(14)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(14)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(14)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(14)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(15)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(15)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(15)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(15)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(16)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(16)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(16)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(16)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(17)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(17)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(17)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(17)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(18)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(18)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(18)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(18)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(19)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(19)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(19)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(19)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(20)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(20)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(20)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(20)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(21)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(21)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(21)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(21)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(22)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(22)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(22)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(22)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(23)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(23)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(23)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(23)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(24)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(24)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(24)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(24)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(25)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(25)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(25)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(25)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(26)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(26)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(26)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(26)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(27)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(27)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(27)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(27)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(28)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(28)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(28)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(28)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(29)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(29)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(29)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(29)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(30)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(30)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(30)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(30)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(31)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(31)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(31)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create0/create(31)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/sy
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/x0
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/x1
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/yout
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(0)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(0)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(0)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(0)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(1)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(1)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(1)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(1)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(2)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(2)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(2)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(2)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(3)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(3)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(3)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(3)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(4)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(4)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(4)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(4)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(5)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(5)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(5)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(5)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(6)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(6)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(6)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(6)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(7)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(7)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(7)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(7)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(8)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(8)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(8)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(8)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(9)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(9)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(9)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(9)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(10)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(10)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(10)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(10)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(11)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(11)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(11)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(11)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(12)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(12)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(12)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(12)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(13)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(13)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(13)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(13)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(14)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(14)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(14)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(14)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(15)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(15)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(15)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(15)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(16)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(16)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(16)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(16)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(17)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(17)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(17)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(17)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(18)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(18)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(18)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(18)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(19)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(19)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(19)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(19)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(20)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(20)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(20)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(20)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(21)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(21)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(21)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(21)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(22)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(22)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(22)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(22)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(23)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(23)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(23)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(23)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(24)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(24)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(24)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(24)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(25)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(25)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(25)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(25)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(26)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(26)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(26)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(26)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(27)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(27)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(27)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(27)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(28)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(28)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(28)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(28)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(29)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(29)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(29)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(29)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(30)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(30)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(30)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(30)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(31)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(31)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(31)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create1/create(31)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/sy
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/x0
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/x1
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/yout
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(0)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(0)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(0)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(0)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(1)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(1)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(1)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(1)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(2)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(2)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(2)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(2)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(3)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(3)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(3)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(3)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(4)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(4)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(4)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(4)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(5)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(5)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(5)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(5)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(6)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(6)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(6)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(6)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(7)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(7)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(7)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(7)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(8)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(8)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(8)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(8)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(9)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(9)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(9)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(9)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(10)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(10)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(10)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(10)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(11)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(11)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(11)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(11)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(12)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(12)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(12)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(12)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(13)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(13)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(13)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(13)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(14)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(14)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(14)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(14)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(15)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(15)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(15)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(15)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(16)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(16)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(16)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(16)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(17)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(17)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(17)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(17)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(18)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(18)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(18)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(18)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(19)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(19)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(19)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(19)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(20)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(20)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(20)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(20)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(21)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(21)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(21)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(21)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(22)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(22)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(22)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(22)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(23)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(23)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(23)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(23)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(24)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(24)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(24)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(24)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(25)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(25)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(25)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(25)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(26)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(26)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(26)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(26)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(27)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(27)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(27)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(27)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(28)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(28)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(28)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(28)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(29)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(29)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(29)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(29)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(30)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(30)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(30)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(30)/chain/y
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(31)/chain/a
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(31)/chain/b
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(31)/chain/s
add wave -noupdate /mips_tb/U_0/EXE/Shift_R/create2/create(31)/chain/y
add wave -noupdate /mips_tb/U_0/MEM/read_data
add wave -noupdate /mips_tb/U_0/MEM/address
add wave -noupdate /mips_tb/U_0/MEM/write_data
add wave -noupdate /mips_tb/U_0/MEM/MemRead
add wave -noupdate /mips_tb/U_0/MEM/Memwrite
add wave -noupdate /mips_tb/U_0/MEM/clock
add wave -noupdate /mips_tb/U_0/MEM/reset
add wave -noupdate /mips_tb/U_0/MEM/write_clock
add wave -noupdate /mips_tb/U_0/MEM/data_memory/wren_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/wren_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/rden_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/rden_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/data_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/data_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/address_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/address_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/clock0
add wave -noupdate /mips_tb/U_0/MEM/data_memory/clock1
add wave -noupdate /mips_tb/U_0/MEM/data_memory/clocken0
add wave -noupdate /mips_tb/U_0/MEM/data_memory/clocken1
add wave -noupdate /mips_tb/U_0/MEM/data_memory/clocken2
add wave -noupdate /mips_tb/U_0/MEM/data_memory/clocken3
add wave -noupdate /mips_tb/U_0/MEM/data_memory/aclr0
add wave -noupdate /mips_tb/U_0/MEM/data_memory/aclr1
add wave -noupdate /mips_tb/U_0/MEM/data_memory/addressstall_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/addressstall_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/byteena_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/byteena_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/q_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/q_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/eccstatus
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_data_reg_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_data_reg_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_q_reg_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_q_tmp_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_q_tmp2_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_q_tmp_wren_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_q_tmp2_wren_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_q_tmp_wren_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_q_reg_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_q_tmp_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_q_tmp2_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_q_output_latch
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_q_ecc_reg_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_q_ecc_tmp_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_current_written_data_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_original_data_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_original_data_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_byteena_mask_reg_a_x
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_byteena_mask_reg_b_x
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_byteena_mask_reg_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_byteena_mask_reg_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_byteena_mask_reg_a_out
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_byteena_mask_reg_b_out
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_byteena_mask_reg_a_out_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_byteena_mask_reg_b_out_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_address_reg_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_address_reg_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_wren_reg_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_wren_reg_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_rden_reg_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_rden_reg_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_read_flag_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_read_flag_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_reread_flag_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_reread_flag_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_reread_flag2_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_reread_flag2_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_write_flag_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_write_flag_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_nmram_write_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_nmram_write_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_indata_aclr_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_address_aclr_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_wrcontrol_aclr_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_indata_aclr_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_address_aclr_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_wrcontrol_aclr_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_outdata_aclr_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_outdata_aclr_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_rdcontrol_aclr_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_byteena_aclr_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_byteena_aclr_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/good_to_go_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/good_to_go_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_core_clocken_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_core_clocken_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_core_clocken_b0
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_core_clocken_b1
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_inclocken0
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_input_clocken_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_outdata_clken_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_outdata_clken_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_outlatch_clken_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_outlatch_clken_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_core_clocken_a_reg
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_core_clocken_b_reg
add wave -noupdate /mips_tb/U_0/MEM/data_memory/default_val
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_data_zero_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_data_zero_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_data_ones_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_data_ones_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/same_clock_pulse0
add wave -noupdate /mips_tb/U_0/MEM/data_memory/same_clock_pulse1
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_force_reread_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_force_reread_a1
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_force_reread_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_force_reread_b1
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_force_reread_signal_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_force_reread_signal_b
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_good_to_write_a
add wave -noupdate /mips_tb/U_0/MEM/data_memory/i_good_to_write_b
add wave -noupdate /mips_tb/U_0/BT/MCLK
add wave -noupdate /mips_tb/U_0/BT/reset
add wave -noupdate /mips_tb/U_0/BT/BTCTL_W
add wave -noupdate /mips_tb/U_0/BT/BTCTL_R
add wave -noupdate /mips_tb/U_0/BT/BTCNT_W
add wave -noupdate /mips_tb/U_0/BT/BTCNT_R
add wave -noupdate -color Magenta /mips_tb/U_0/BT/BTIFG
add wave -noupdate /mips_tb/U_0/BT/BTHOLD
add wave -noupdate /mips_tb/U_0/BT/BTHOLD_old
add wave -noupdate /mips_tb/U_0/BT/BTSSEL
add wave -noupdate /mips_tb/U_0/BT/BTIPx
add wave -noupdate /mips_tb/U_0/BT/CLK
add wave -noupdate /mips_tb/U_0/BT/CLK_old
add wave -noupdate -color Cyan /mips_tb/U_0/BT/MCLK2
add wave -noupdate /mips_tb/U_0/BT/MCLK4
add wave -noupdate /mips_tb/U_0/BT/MCLK8
add wave -noupdate /mips_tb/U_0/BT/clk_div_cnt
add wave -noupdate /mips_tb/U_0/BT/clk_div_fixed
add wave -noupdate /mips_tb/U_0/BT/Counter
add wave -noupdate /mips_tb/U_0/INTCTL/clock
add wave -noupdate /mips_tb/U_0/INTCTL/reset
add wave -noupdate /mips_tb/U_0/INTCTL/CS
add wave -noupdate -color Gold /mips_tb/U_0/INTCTL/INTA
add wave -noupdate /mips_tb/U_0/INTCTL/irq0
add wave -noupdate /mips_tb/U_0/INTCTL/irq1
add wave -noupdate /mips_tb/U_0/INTCTL/irq2
add wave -noupdate -color Magenta /mips_tb/U_0/INTCTL/irq3
add wave -noupdate /mips_tb/U_0/INTCTL/IE_W
add wave -noupdate /mips_tb/U_0/INTCTL/IFG_W
add wave -noupdate /mips_tb/U_0/INTCTL/IE_R
add wave -noupdate /mips_tb/U_0/INTCTL/IFG_R
add wave -noupdate /mips_tb/U_0/INTCTL/IFG_writebit
add wave -noupdate /mips_tb/U_0/INTCTL/ISR_MemAdrs
add wave -noupdate /mips_tb/U_0/INTCTL/INTR
add wave -noupdate /mips_tb/U_0/INTCTL/tmp_address
add wave -noupdate /mips_tb/U_0/INTCTL/BTIE
add wave -noupdate /mips_tb/U_0/INTCTL/KEY3IE
add wave -noupdate /mips_tb/U_0/INTCTL/KEY2IE
add wave -noupdate /mips_tb/U_0/INTCTL/KEY1IE
add wave -noupdate /mips_tb/U_0/INTCTL/BTIFG
add wave -noupdate /mips_tb/U_0/INTCTL/KEY3IFG
add wave -noupdate /mips_tb/U_0/INTCTL/KEY2IFG
add wave -noupdate /mips_tb/U_0/INTCTL/KEY1IFG
add wave -noupdate /mips_tb/U_0/INTCTL/BT_irq_old
add wave -noupdate /mips_tb/U_0/INTCTL/KEY3_irq_old
add wave -noupdate /mips_tb/U_0/INTCTL/KEY2_irq_old
add wave -noupdate /mips_tb/U_0/INTCTL/KEY1_irq_old
add wave -noupdate /mips_tb/U_0/INTCTL/BT_irq
add wave -noupdate /mips_tb/U_0/INTCTL/KEY3_irq
add wave -noupdate /mips_tb/U_0/INTCTL/KEY2_irq
add wave -noupdate /mips_tb/U_0/INTCTL/KEY1_irq
add wave -noupdate /mips_tb/U_0/INTCTL/TYPEx
add wave -noupdate /mips_tb/U_0/INTCTL/intr_BT
add wave -noupdate /mips_tb/U_0/INTCTL/intr_K3
add wave -noupdate /mips_tb/U_0/INTCTL/intr_K2
add wave -noupdate /mips_tb/U_0/INTCTL/intr_K1
add wave -noupdate /mips_tb/U_0/INTCTL/IFG_writebit_old
add wave -noupdate /mips_tb/U_0/INTCTL/status
add wave -noupdate /mips_tb/U_0/bitsToHex0/bits
add wave -noupdate /mips_tb/U_0/bitsToHex0/hex
add wave -noupdate /mips_tb/U_0/bitsToHex1/bits
add wave -noupdate /mips_tb/U_0/bitsToHex1/hex
add wave -noupdate /mips_tb/U_0/bitsToHex2/bits
add wave -noupdate /mips_tb/U_0/bitsToHex2/hex
add wave -noupdate /mips_tb/U_0/bitsToHex3/bits
add wave -noupdate /mips_tb/U_0/bitsToHex3/hex
add wave -noupdate /mips_tb/U_1/ALU_result_out
add wave -noupdate /mips_tb/U_1/Branch_out
add wave -noupdate /mips_tb/U_1/Instruction_out
add wave -noupdate /mips_tb/U_1/Memwrite_out
add wave -noupdate /mips_tb/U_1/PC
add wave -noupdate /mips_tb/U_1/Regwrite_out
add wave -noupdate /mips_tb/U_1/Zero_out
add wave -noupdate /mips_tb/U_1/read_data_1_out
add wave -noupdate /mips_tb/U_1/read_data_2_out
add wave -noupdate /mips_tb/U_1/write_data_out
add wave -noupdate /mips_tb/U_1/clock
add wave -noupdate /mips_tb/U_1/reset
add wave -noupdate /mips_tb/U_1/mw_U_0clk
add wave -noupdate /mips_tb/U_1/mw_U_0disable_clk
add wave -noupdate /mips_tb/U_1/mw_U_1pulse
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {3631441 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 238
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {1162443 ps} {8912075 ps}
